CREATE DATABASE seminarska;
USE seminarska;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    username VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE seasons(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    year INTEGER NOT NULL
);

CREATE TABLE races(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    date DATE NOT NULL,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    season_id INTEGER,
    CONSTRAINT FK_season FOREIGN KEY(season_id) REFERENCES seasons(id)
);

CREATE TABLE images (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    path VARCHAR(255) NOT NULL,
    season_id INT,
    CONSTRAINT FK_image_season_id FOREIGN KEY (season_id) REFERENCES seasons (id)
);


CREATE TABLE watched(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CONSTRAINT FK_race FOREIGN KEY(race_id) REFERENCES race(id),
    CONSTRAINT FK_user FOREIGN KEY(user_id) REFERENCES user(id)
);

ALTER TABLE seasons 
ADD UNIQUE (year); 