<?php
include_once('dependencies.php');
?>
<body>
    <?php
    if(isset($_SESSION['user']))
    {
      include_once('homepage.php');
    }
    else
    {
      include_once('logedouthomepage.php');
    }
    ?>
</body>